image: {image}

variables:
  GIT_DEPTH: 10
  # R_LIBS is not empty in rocker images
  R_LIBS: ${CI_PROJECT_DIR}/ci/lib:${R_LIBS}
  R_LIBS_USER: ${CI_PROJECT_DIR}/ci/lib

cache:
  key: cache-default
  paths:
      - ${R_LIBS_USER}

stages:
  - book-create
  - deploy

book-main:
    stage: book-create
    script:
        - lsb_release -c
        - R -e "sessionInfo()"
        - echo "Library path for packages :" $R_LIBS_USER
        - mkdir -p $R_LIBS_USER
        - Rscript -e 'if(!requireNamespace("pak", quietly = TRUE)) {install.packages("pak")}'
        - Rscript -e 'pak::pkg_install(pkg = c("attachment", "tinytex", "usethis"), upgrade = {upgrade})'
        - Rscript -e 'if (!file.exists("DESCRIPTION")) {usethis::use_description(check_name = FALSE)}'
        - >
          Rscript -e 'imports <- unique(c("bookdown", "knitr", "pagedown",
            attachment::att_from_rmds(".", recursive = FALSE)));
            if (packageVersion("attachment") <= "0.2.2") {
              attachment::att_to_desc_from_is(path.d = "DESCRIPTION", imports = imports)
              } else {attachment::att_to_desc_from_is(path.d = "DESCRIPTION", imports = imports, must.exist = FALSE)}'
        - Rscript -e 'pak::local_install_deps(root = ".", upgrade = {upgrade})'
        - Rscript -e 'pak::local_install_dev_deps(root = ".", upgrade = {upgrade})'
        - Rscript -e 'if(!tinytex::is_tinytex()) tinytex::install_tinytex(force = TRUE)'
        - mkdir -p public
        - Rscript -e 'bookdown::render_book("index.Rmd", output_format = "bookdown::bs4_book", clean = FALSE, output_dir = "public")'
        # - Rscript -e 'bookdown::render_book("index.Rmd", output_format = "bookdown::gitbook", clean = FALSE, output_dir = "public")'
        - Rscript -e 'bookdown::render_book("index.Rmd", output_format = "bookdown::pdf_book", clean = FALSE, output_dir = "public")'
        - Rscript -e 'output_file <- bookdown::render_book("index.Rmd", output_format = "pagedown::html_paged", clean = FALSE);file.copy(output_file, "public/_pagedown.html")'
    artifacts:
        paths:
            - public
        expire_in: 30 days

pages:
    stage: deploy
    script:
        - echo "book deployment"
    artifacts:
        paths:
            - public
    only:
        - master
        - main

